### ISSUE TITLE
Segfaults after certain amount of queries

### ISSUE THREAD

**Issue by waterlink** [waterlink/crystal-mysql#24]
I assume that the time has come to fix this: https://github.com/waterlink/crystal-mysql/blob/master/src/mysql/connection.cr#L96-L100

**Comment by waterlink** [comment]
Nope, does not fix it :(

**Comment by alex-fedorov** [comment]
Somehow on Mac OS X it is not a problem.

Looks like a problem with wrong `struct`s mapping.

**Comment by waterlink** [comment]
https://travis-ci.org/waterlink/mysql_adapter.cr/builds/78137837
