### ISSUE TITLE
how to install the mysql client lib

### ISSUE THREAD

**Issue by michaeldesu** [waterlink/crystal-mysql#39]
Hi,

Thanks for making this shard available. I'm having some trouble to get it going on Mac OS X. 

After creating a simple app to connect, I get an error:

ld: library not found for -lmysqlclient

I've tried to install it via:

brew install mysql --client-only --universal
& 
installing the mysql-connector-c-6.1.6-osx10.8-x86_64.dmg from https://dev.mysql.com/downloads/connector/c/

but to no avail. Any tip or suggestion is appreciated. 

Thanks.

**Comment by waterlink** [comment]
Hi, 

I didn't had such problem. `brew install mysql` just worked. 

Maybe you can find this helpful: https://support.apple.com/en-us/HT200150

**Comment by michaeldesu** [comment]
Thanks alot for your help - your brew suggestion worked.

Look forward to future updates!

Cheers.
