### ISSUE TITLE
Linker issue

### ISSUE THREAD

**Issue by incognick** [waterlink/crystal-mysql#41]
I'm getting an error when trying to run my simple database program.

```
require "mysql"
conn = MySQL.connect("127.0.0.1", "root", "1234", "blog", 3306_u16, nil)
```

The error I get:

```
/usr/bin/ld: cannot find -lmysqlclient 
collect2: error: ld returned 1 exit status 
Error: execution of command failed with code: 1: 'cc -o "blog" "${@}"  -rdynamic  -lmysqlclient opt/crystal/src/ext/libcrystal.a -levent -lrt -lpcre -lgc -lpthread -ldl'
```

I'm running Ubuntu 14.04 LTS and mysql 5.5 with mysql-client-5.5 installed.  I tried to add the path to the LD_LIBRARY_PATH prior to running the `crystal build` command but doesn't seem to help.  

Any ideas?  Thanks!

**Comment by incognick** [comment]
sorry fixed my own issue :)  Hopefully this helps someone else.  

```
sudo apt-get install libmysqlclient-dev
```

**Comment by waterlink** [comment]
Hmm, Probably we need to amend installation instructions for different
platforms (at least Ubuntu, Mac OS X).

Are you up to making a PR to README (at least for Ubuntu)?

## 

Best Regards,
Oleksii Fedorov,
Competent Programmer,
TDD, Microservices, Ruby, Clojure, Go and more,
+49 15757 486 476
