### ISSUE TITLE
Crystal 0.16.0 Could not compile the Library.

### ISSUE THREAD

**Issue by GuneshRaj** [waterlink/crystal-mysql#44]
Using the latest Crystal 0.16.0 on a test project, I faced this issue:

Error in ./libs/mysql/mysql/types.cr:65: can't extend non-abstract struct MySQL::Types::Value

```
struct Blob < Value
       ^
```

**Comment by waterlink** [comment]
Hi @GuneshRaj 

Thanks for reporting!

This is fixed in the latest release `0.4.3`.
